### ISSUE TITLE
i3config syntax isn't quite compatible with sway

### ISSUE THREAD

**Issue by rpigott** [vim/vim#10231]
The new i3config syntax isn't quite compatible with sway's config syntax.

Although we try to retain compatibility with i3, there are some cases that compel us to introduce new keywords and features in sway's configuration, mostly to replace features that used to be part of X configuration that must now be handled in the compositor.

So the highlighter doesn't understand `bindswitch` or `input`/`output` sway config directives, for example. It also doesn't understand the `include` directive, even though i3 has since added support for this originally sway-specific feature in i3/i3#4420. The highlight path */.sway/config also is not appropriate for sway since sway does not check that path for its configuration (https://man.archlinux.org/man/community/sway/sway.1.en#CONFIGURATION).

Do you think we should try to keep an i3 and sway compatible syntax definition or make two separate syntaxes? I really wouldn't mind if not for the obnoxious error highlighting, so that's what I'm trying to correct. If preferable, maybe we can just be less strict about highlighting errors.

**Comment by dkearns** [comment]
I'm not really familiar with either but in my experience it's almost always easier to create a new filetype.  It sounds like you could just source the i3 syntax file and make additions.

**Comment by brammool** [comment]
If two filetypes are similar but not the same, then it's usually easier to have two filetypes, and have the syntax perhaps share the common part.  If one is a superset of the other, then include that other and add on top of it.

**Comment by hiqua** [comment]
@RPigott:
1. please see the [PR](https://github.com/vim/vim/pull/7969) for the context, basically it's a best-effort thing, with the hope that vim is better with than without these syntax files
2. given this, I should probably remove the error highlighting stuff given that it's bound to break too often to be a real gain. This should solve the main issues with sway
3. until somebody chimes in to support sway config properly in vim, I think it's fine to have some minimal support in the same files
4. `The highlight path */.sway/config also is not appropriate for sway since sway does not check that path for its configuration (https://man.archlinux.org/man/community/sway/sway.1.en#CONFIGURATION).`: I think you meant that sway doesn't check every path ending with `.sway/config`, but I think this is fine given the rest of the filetype.vim file. It's unlikely to have a path ending with this which wouldn't be a sway config file. I think the other paths mentioned in your link are already covered, so there shouldn't be any change required for this, but let me know if I've missed something.

I'll create a PR for 2. Somebody already added the `include` directive. If somebody wants to create a PR for missing sway directives feel free to do so!

**Comment by habamax** [comment]
@hiqua there are other i3ConfigErrors:


![image](https://user-images.githubusercontent.com/234774/172039941-a635f002-694c-4515-8b46-b2676dddecfc.png)

**Comment by hiqua** [comment]
@habamax please see the PR linked above.

**Comment by habamax** [comment]
@hiqua hmm, I was thinking it was already included as I can see a lot less errors.

Okay, I have grabbed syntax file from the PR, put it into `~/.vim/syntax/i3config.vim`

I can still see error for `smart_borders off`:

![image](https://user-images.githubusercontent.com/234774/172049933-de5af2b5-3559-49e4-a2c3-50e7716b9252.png)


I guess the rest errors from the prev message are stil relevant.

**Comment by habamax** [comment]
Or maybe I am just didn't understand what is this all about. Then sorry for the noise, I was thinking one of the goal is to just to remove error highlighting.

For this I would expect a "single line" to be removed to fix all the mess:
```
" Error
syn match i3ConfigError /.*/
```

Maybe additional 
```
hi! def link i3ConfigError                           Error
```

![image](https://user-images.githubusercontent.com/234774/172050099-f28f20de-1c31-41d9-85c8-e9e2e8534066.png)

**Comment by habamax** [comment]
And yes, sorry, I have checked the wrong PR :)

**Comment by brammool** [comment]
Can this be closed now?

**Comment by RPigott** [comment]
Yes, sorry I was away. I'm satisfied with those PRs, let's close this.
