### ISSUE TITLE
Syntax highlighting broken on sh files

### ISSUE THREAD

**Issue by KaspervdHeijden** [vim/vim#10982]
On vim 9.0, it seems that the syntax highlighing is broken:

![image](https://user-images.githubusercontent.com/20627978/186848296-027e2581-a04f-44a4-88e2-9bc1fde0aaec.png)

But if I unquote the multiline it renders fine:
![image](https://user-images.githubusercontent.com/20627978/186848428-d48797a4-7d1a-4182-82fc-607d32a18a7b.png)

**Comment by brammool** [comment]
AFAIK the syntax is exactly the same, this is likely a difference in the setup.  Check the variables related to shell highlighting (it's a bit tricky with subtle differences between shell dialects).

**Comment by lacygoill** [comment]
[Posting text instead of pictures](https://meta.stackoverflow.com/a/285557) would have helped to make tests quicker.

---

This patch should fix the issue:
```diff
diff --git a/runtime/syntax/sh.vim b/runtime/syntax/sh.vim
index e44699faa..7ae8c479c 100644
--- a/runtime/syntax/sh.vim
+++ b/runtime/syntax/sh.vim
@@ -386,7 +386,7 @@ elseif !exists("g:sh_no_error")
  syn region  shExDoubleQuote	matchGroup=Error start=+\$"+ skip=+\\\\\|\\.+ end=+"+	contains=shStringSpecial
 endif
 syn region  shSingleQuote	matchgroup=shQuote start=+'+ end=+'+		contains=@Spell	nextgroup=shSpecialStart,shSpecialSQ
-syn region  shDoubleQuote	matchgroup=shQuote start=+\%(\%(\\\\\)*\\\)\@<!"+ skip=+\\.+ end=+"+			contains=@shDblQuoteList,shStringSpecial,@Spell	nextgroup=shSpecialStart
+syn region  shDoubleQuote	matchgroup=shQuote start=+\%(\%(\\\\\)*\\\)\@<!"+ skip=+\\.+ end=+"+			contains=@shDblQuoteList,shStringSpecial,shSubSh,@Spell	nextgroup=shSpecialStart
 syn match   shStringSpecial	"[^[:print:] \t]"			contained
 syn match   shStringSpecial	"[^\\]\zs\%(\\\\\)*\(\\[\\"'`$()#]\)\+"			nextgroup=shComment
 syn match   shSpecialSQ	"[^\\]\zs\%(\\\\\)*\(\\[\\"'`$()#]\)\+"		contained	nextgroup=shBkslshSnglQuote,@shNoZSList
```
But maybe the syntax group `shSubSh` should instead be included inside the `@shDblQuoteList` cluster.  I don't know.

**Comment by Shane-XB-Qian** [comment]
here, the MRE :
```sh
output="$(
	foo
	sed 's/"//g'
	bar
)"
```

// BTW: not sure why { why difference? :-) #10968 } but for this part looks the neovim syntax looked a bit nicer?
// but why different? :-)
![image](https://user-images.githubusercontent.com/13550529/186943983-689df30a-fc1e-4092-b8f1-8b7d0d2067a0.png)

**Comment by Shane-XB-Qian** [comment]
just a terrible joke, pls donot mind.. :-)
@KaspervdHeijden here you can workaround it by a dummy `\"` then gone.

**Comment by KaspervdHeijden** [comment]
@lacygoill I am aware that posting pictures may be less clear, however, since the nature of syntax highlighting is graphical I think this does demonstrate the problem at first glance. Having said that I could have explained the diff better.

Having unbalanced and/or nested quotes seems to be the issue at hand.

**Comment by lacygoill** [comment]
Including an image is fine.  But if we can't read the contents of the images (I have difficulties reading text on a dark background), here is what remains:

   > On vim 9.0, it seems that the syntax highlighing is broken:
   > But if I unquote the multiline it renders fine:

That's not enough to help.

And even if we can read the text, having to read and write all of it takes time and is error-prone:
```sh
#!/usr/bin/env sh

if ! command -v pactl >/dev/null; then
    echo 'no pactl found' >&2
    exit 2
fi

cmd="${1}"
case "${cmd}" in
    'set-volume') pactl set-sink-volume @DEFAULT_SINK@ "${2:-10}%" ;;
    'toggle-mute') pactl set-sink-mute @DEFAULT_SINK@ toggle       ;;
    'current-sink')
        output="$(
            pactl list sinks | \
                grep -A1 'node.name = ' | \
                grep -A1 "$(pactl get-default-sink)" | \
                grep 'node.nick = ' | \
                grep -o '".\+"' | \
                sed 's/"//g'
            )"

            if [ -z "${output}" ]; then
                output="$(
                    pactl list sinks | \
                        gep -A1 'Name: ' | \
                        grep -v '^--' \
                        awk '!(NR % 2) { print p ":" $0 }{ p = $0 }' | \
                        grep '^\s\+Name' | \
                        cut -c8- | \
                        sed 's/Description://; s/:\s\+/: /' | \
                        grep "$(pactl get-default-sink)" | \
                        awk -F: ' '{print $2}'
                )"
            fi

            echo "${output}"

            ;;
```
---

   > Having unbalanced and/or nested quotes seems to be the issue at hand.

I think the issue is that a double-quoted string does not contain enough syntax items, which can allow for a nested double quote to end prematurely the outer string.  The previous patch should fix the issue (if someone could test and confirm, that would help).

**Comment by Shane-XB-Qian** [comment]
i guess bram had adjusted the balance (or direction) of syntax perf vs correction a bit after that day that my joke comment :-)
but here looks also the 'double-quotion' truly was not syntax correctly.. @cecamp

**Comment by KaspervdHeijden** [comment]
@Shane-XB-Qian the file where is seems to be broken:

My vimrc is very basic, I do not have plugins. See https://gitlab.com/kaspervdheijden/dotfiles/-/blob/master/config/vimrc.vim.

<details>
  <summary>Source file</summary>

```sh
#!/usr/bin/env sh

if ! command -v pactl >/dev/null; then
    echo 'no pactl found' >&2
    exit 2
fi

friendlyName()
{
	item="${1}"
	output="$(
	    pactl list sinks | \
		grep -A1 'node.name = ' | \
		grep -A1 "${item}" | \
		grep 'node.nick = ' | \
		grep -o '".\+"' | \
		sed 's/"//g'
	)"

	if [ -z "${output}" ]; then
	    output="$(
		pactl list sinks | \
		    grep -A1 'Name: ' | \
		    grep -v '^--' | \
		    awk '!(NR % 2) { print p ":" $0 }{ p = $0 }' | \
		    grep '^\s\+Name' | \
		    cut -c8- | \
		    sed 's/Description://; s/:\s\+/: /' | \
		    grep "${item}" | \
		    awk -F': ' '{print $2}'
	    )"
	fi

    if [ -z "${output}" ]; then
        return 1
    fi

	echo "${output}"
}

cmd="${1}"
case "${cmd}" in
    'set-volume')  pactl set-sink-volume @DEFAULT_SINK@ "${2:-10}%" ;;
    'toggle-mute') pactl set-sink-mute @DEFAULT_SINK@ toggle        ;;
    'current-sink') friendlyName "$(pactl get-default-sink)"        ;;
    'select-output')
        sinks="$(pactl list sinks short | awk '{print $2}')"
        if [ -z "${sinks}" ]; then
            echo 'no sinks' >&2
            exit 3
        fi

        current="$(pactl get-default-sink)"
        mapping="$(for sink in $(echo "${sinks}" | xargs); do echo "${sink}:$(friendlyName "${sink}")"; done)"
        chosen="$( \
            echo "${mapping}" | \
            awk -F':' -v cur="${current}" '{ s = ""; if ($1 == cur) { s = "* "; }  print s$2; }' | \
            sort -r | \
            rofi -dmenu -i -p 'Select output device: ' |
            sed 's/^* //' \
        )"

        if [ -z "${chosen}" ]; then
            exit
        fi

        sink="$(echo "${mapping}" | awk -F':' -v chosen="${chosen}" '$2 == chosen { print $1; }' | head -n1)"
        if [ -z "${sink}" ]; then
            echo "chosen sink name not found for '${chosen}'" >&2
            exit 4
        fi

        if [ "${sink}" = "${current}" ]; then
            echo "already set to '${sink}'"
        elif ! pactl set-default-sink "${sink}"; then
            echo "error setting default sink to '${sink}'" >&2
            exit 5
        fi

        ;;
    'startup')
        sinks="$(pactl list sinks | grep 'Name: ')"
        if [ -z "${sinks}" ]; then
            exit
        fi

        item="$(echo "${sinks}" | grep 'Name: bluez_output.')"
        if [ -z "${item}" ]; then
            item="$(echo "${sinks}" | tail -n1)"
        fi

        pactl set-default-sink "$(echo "${item}" | cut -c8-)"

        ;;
    *)
        echo "unrecognized command '${cmd}'" >&2
        exit 6

        ;;
esac
```
</details>

Syntax seems to be fine:
```sh
[vanderheijdenk@spaceship zsh Linux ~/.config/sway 2022-08-29 11:21 master*]
% shellcheck scripts/sound-manager
[vanderheijdenk@spaceship zsh Linux ~/.config/sway 2022-08-29 11:21 master*]
% echo $?
0
[vanderheijdenk@spaceship zsh Linux ~/.config/sway 2022-08-29 11:21 master*]
%
```

But still renderes wrong:
![image](https://user-images.githubusercontent.com/20627978/187168543-086461bd-6409-47b6-ad6b-cccf29f7dcd7.png)

**Comment by Shane-XB-Qian** [comment]
i said you can workaround it by a dummy `\"`, or pls wait sh runtime maintainer to fix it.
// nothing else... as for that `joke` was about vim src code of syntax impl itself, you might need not to mind this. :-)

**Comment by Shane-XB-Qian** [comment]
@cecamp  yesterday's sh runtime update seems did not fix this. fyi.
