### ISSUE TITLE
Strange value of v:shell_error when calling system() with silent

### ISSUE THREAD

**Issue by hexchain** [vim/vim#1196]
ref: https://github.com/majutsushi/tagbar/issues/352

```
$ cat repro 
silent let foo = system('echo foobar')
echo 'silent shell_error: ' . v:shell_error . ' ' . foo
$ vim -N -u repro
silent shell_error: 0 foobar

Press ENTER or type command to continue
$ # Totally fine so far...
$ vim -N -u NONE
<- Then type ":so repro" (without quotes) in vim
silent shell_error: -1 foobar
<- Now this is strange...
```

This problem does not reproduce on vim 8.0.0013. `git bisect` shows the first bad commit is 97792de.

Versions:
```
$ cat /etc/*release*
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

$ pacman -Q vim vim-runtime
vim 8.0.0046-2
vim-runtime 8.0.0046-2
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 24 2016 17:34:44)
Included patches: 1-46
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```

**Comment by chrisbra** [comment]
FWIW, i don't see this with vim 8.0.46, it shows the same output as 8.0.13

**Comment by chrisbra** [comment]
What are your various shell settings? BTW: -1 means, an error occured when trying to execute the shell command.

**Comment by hexchain** [comment]
What could be affecting this?

`:echo &shell` -> `/bin/bash`

```
$ pacman -Q bash
bash 4.3.046-1
```

**Comment by xaizek** [comment]
@hexchain, if this is introduced by one of recent revisions, using `git bisect` could be the fastest way of finding the cause.

**Comment by hexchain** [comment]
Will do.

**Comment by hexchain** [comment]
`git bisect` shows the first bad commit is 97792de2762cc79cc365a8a0b858f27753179577

**Comment by chrisbra** [comment]
Are you using some jobs?

**Comment by hexchain** [comment]
No, I did the bisect entirely based on the example, and of course with `vim -N -u NONE` every time.

**Comment by ichizok** [comment]
I couldn't reproduce it on my some envs...
(Vim 8.0.55/macOS 10.12, Ubuntu 16.04 (VM), ...)

I'd like to ask some:
- Is it reproduce always?
- check the following cases;
  - use other variable at second `system()` (`silent let bar = ...`)
  - exchange the order of `let foo = ...` and `silent let foo = ..`
  - only do `silent let foo = system(...)`

**Comment by hexchain** [comment]
Yes, it always reproduces.

And a smaller test case:

```
$ cat repro 
silent let sth2 = system('echo something2')
echo 'silent shell_error: ' . v:shell_error . ' ' . sth2
```

`vim -N -u repro` (This one is good):

```
silent shell_error: 0 something2

Press ENTER or type command to continue
```

`vim -N -u NONE` then `:so repro`:

```
silent shell_error: -1 something2
```

**Comment by ichizok** [comment]
@hexchain  Thank you.
Could you apply this patch and do `repro` again?
https://gist.github.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1

**Comment by hexchain** [comment]
@ichizok Things just got a bit more interesting:
`vim -N -u repro` (This one is still good):

```
silent shell_error: 0 something2
```

`vim -N -u NONE` then `:so repro`:

```
silent shell_error: 1 something2
```

**Comment by ichizok** [comment]
I updated patch. Please try it.
https://gist.github.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1

**Comment by hexchain** [comment]
New patch: same result as the beginning (returns -1).

**Comment by ichizok** [comment]
Hmm.. could you do `strace`?

Run `strace` after vim starting, and do `:so repro`:

`vim -Nu NONE`

`sudo strace -e wait4,kill -p $(pgrep vim)` on another console,

and then `:so repro` on vim

**Comment by hexchain** [comment]
strace result: https://paste.xinu.at/FRid56/

**Comment by ichizok** [comment]
Thank you. I fixed patch.
https://gist.github.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1

**Comment by ichizok** [comment]
What is result of `echo $TERM`?

**Comment by vim-ml** [comment]
Hi Kiichi,

Perhaps you should enclose all of the added lines in the below directive?

#if defined(FEAT_JOB_CHANNEL) && !defined(USE_SYSTEM)
  ...
#endif ?

(use `#if defined(FEAT_JOB_CHANNEL) && !defined(USE_SYSTEM)` instead of `# ifdef FEAT_JOB_CHANNEL`)

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by hexchain** [comment]
@ichizok With the latest patch I still get "-1".

My `$TERM` is `xterm-256color`. If I set it to `linux`, `vt100`, `screen{,-256color}` or even `dumb` the problem just disappears (returns "0"). But `xterm` and `xterm-256color` gives me wrong result.

**Comment by ichizok** [comment]
@h-east Thank you for your indication.

The followings are in `#else` block of`#ifdef USE_SYSTEM`.
https://gist.github.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1/c60485d51b3e3395c69badadcc4bd3315cd8f3b5#file-issue1196-patch-L20-L22
https://gist.github.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1/c60485d51b3e3395c69badadcc4bd3315cd8f3b5#file-issue1196-patch-L30-L32

And I fixed it, as you pointed out.
https://gist.github.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1/c60485d51b3e3395c69badadcc4bd3315cd8f3b5#file-issue1196-patch-L42-L45

**Comment by ichizok** [comment]
@hexchain Could you do `strace` last patched vim?

**Comment by hexchain** [comment]
last strace:
- TERM=`xterm-256color`: https://paste.xinu.at/l3wfu/
- TERM=`linux`: https://paste.xinu.at/SKxXEL/

**Comment by ichizok** [comment]
Hmm, I thought last patch inhibits `wait4(-1, ...)` (called in `job_check_ended()`) while `system()` executing...
Just in case, could you make sure vim has been applied my last patch?
(Revision4, raw: https://gist.githubusercontent.com/ichizok/82b1a51f5d4c8e5c978911fbb674efc1/raw/c60485d51b3e3395c69badadcc4bd3315cd8f3b5/issue1196.patch)

**Comment by hexchain** [comment]
Yes, you are right. I must have done something wrong.

Re-downloaded your last patch and applied at git master, `v:shell_error` was 0 and those `wait4` calls were gone. Log: https://paste.xinu.at/rsXA/

Just curious, how can `$TERM` affect this behavior?

**Comment by ichizok** [comment]
`system()` waits process complete by [`wait4pid()`](https://github.com/ichizok/vim/blob/a1f4cb9/src/os_unix.c#L5015) and;

```
wait4pid()
  mch_delay()
    settmode()
      check_for_codes_from_term()
```

In `check_for_codes_from_term()`, if [`xt_index_out != 0 && xt_index_out != xt_index_in`](https://github.com/ichizok/vim/blob/a1f4cb9/src/term.c#L5896),
`vpeekc()` is called, eventually `parse_queued_messages()`( and `job_check_ended()`) is called.

value of `xt_index_out` changes [here](https://github.com/ichizok/vim/blob/a1f4cb9/src/term.c#L5788), those processing depends on terminal (xterm?) environment, i.e. `TERM`.

**Comment by ichizok** [comment]
@brammool Thank you.

Additionally, I'd like to inhibit unneeded checking job-ended (calling `wait4(-1, ...)`), when there is no job.

``` diff
diff --git a/src/channel.c b/src/channel.c
--- a/src/channel.c
+++ b/src/channel.c
@@ -4671,6 +4671,9 @@ job_check_ended(void)
 {
     int                i;

+    if (first_job == NULL)
+       return;
+
     for (i = 0; i < MAX_CHECK_ENDED; ++i)
     {
        job_T   *job = mch_detect_ended_job(first_job);
```
