### ISSUE TITLE
c file marco syntax error in 8.0.0086

### ISSUE THREAD

**Issue by fcying** [vim/vim#1257]
If I use `#if 0  #endif`, the code after `#endif` will display error.
it's display ok in 8.0.0040.

8.0.0040
![vim840](https://cloud.githubusercontent.com/assets/106934/20338178/5d209566-ac10-11e6-94cc-9168b5c1d656.jpg)

8.0.0086
![vim850](https://cloud.githubusercontent.com/assets/106934/20338186/6849c5b6-ac10-11e6-906e-386712fd0353.jpg)

use `#if 1`
![vimok](https://cloud.githubusercontent.com/assets/106934/20338194/74385f86-ac10-11e6-87be-6f0f04b15fed.jpg)

**Comment by mattn** [comment]
@brammool this should be fixed with this: https://github.com/vim/vim/issues/1202#issuecomment-256805773

**Comment by vim-ml** [comment]
Hi mattn and Bram,

I found a line for which the addition of `\zs` is forgotten.

## Patch attached.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by mattn** [comment]
updated patch. thank you

**Comment by brammool** [comment]
Jason wrote:

> If I use `#if 0  #endif`, the code after `#endif` will display error.
> it's display ok in 8.0.0040.
> 
> 8.0.0040
> ![vim840](https://cloud.githubusercontent.com/assets/106934/20338178/5d209566-ac10-11e6-94cc-9168b5c1d656.jpg)
> 
> 8.0.0086
> ![vim850](https://cloud.githubusercontent.com/assets/106934/20338186/6849c5b6-ac10-11e6-906e-386712fd0353.jpg)
> 
> use `#if 1`
> ![vimok](https://cloud.githubusercontent.com/assets/106934/20338194/74385f86-ac10-11e6-87be-6f0f04b15fed.jpg)

Thanks for reporting.  I added \zs items to have the highlighting start
at the #endif instead of the spaces before it, but that changed the
order in which items match.  I'll revert one of the \zs items, that
makes this work again.  But look out for any related problems.

## 

The History of every major Galactic Civilization tends to pass through
three distinct and recognizable phases, those of Survival, Inquiry and
Sophistication, otherwise known as the How, Why and Where phases.
For instance, the first phase is characterized by the question 'How can
we eat?' the second by the question 'Why do we eat?' and the third by
the question 'Where shall we have lunch?'
        -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

> I found a line for which the addition of `\zs` is forgotten.
> Patch attached.

Unfortunately that doesn't fix it.  Only remove \zs in the other
cCppOutIf2 appears to fix it.

## 

The startling truth finally became apparent, and it was this: Numbers
written on restaurant checks within the confines of restaurants do not follow
the same mathematical laws as numbers written on any other pieces of paper in
any other parts of the Universe.  This single statement took the scientific
world by storm.  So many mathematical conferences got held in such good
restaurants that many of the finest minds of a generation died of obesity and
heart failure, and the science of mathematics was put back by years.
        -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
This will fix with simply remove `^` but seems big change because this still might be unknown issues.

**Comment by fcying** [comment]
I test by 8.0.0092, it's fix, thanks~~

**Comment by vim-ml** [comment]
Hi Bram and list!

2016-11-17(Thu) 22:48:45 UTC+9 Bram Moolenaar:

> Hirohito Higashi wrote:
> 
> > I found a line for which the addition of `\zs` is forgotten.
> > Patch attached.
> 
> Unfortunately that doesn't fix it.  Only remove \zs in the other
> cCppOutIf2 appears to fix it.

Ah, I just understand!
And I found that the problem still remains.

```
void main()
{
    #if 0
    int i = 0;
    #else
    #endif

    int j = 0;
}
```

See the attached image file `wrong_highlight_in_c.png`.

I think that `\zs` should not be specified for `syn region` where `contained` is specified.
Because `\zs` is already in use at the higher level match.
If we use it in `syn region contained`, the regular expression of the start= and the end= will not match.

I wrote a patch. (Attached)

## Check it please.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

> 2016-11-17(Thu) 22:48:45 UTC+9 Bram Moolenaar:
> 
> > Hirohito Higashi wrote:
> > 
> > > I found a line for which the addition of `\zs` is forgotten.
> > > Patch attached.
> > 
> > Unfortunately that doesn't fix it.  Only remove \zs in the other
> > cCppOutIf2 appears to fix it.
> 
> Ah, I just understand!
> And I found that the problem still remains.
> 
> ```
> void main()
> {
>   #if 0
>   int i = 0;
>   #else
>   #endif
> 
>   int j = 0;
> }
> ```
> 
> See the attached image file `wrong_highlight_in_c.png`.
> 
> I think that `\zs` should not be specified for `syn region` where `contained` is specified.
> Because `\zs` is already in use at the higher level match.
> If we use it in `syn region contained`, the regular expression of the start= and the end= will not match.
> 
> I wrote a patch. (Attached)
> Check it please.

Thanks.  Yeah, adding those \zs was a bad idea.

## 

Q. What happens to programmers when they die?
A: MS-Windows programmers are reinstalled.  C++ programmers become undefined,
   anyone who refers to them will die as well. Java programmers reincarnate
   after being garbage collected, unless they are in permgen, in which case
   they become zombies.  Zimbu programmers leave a stack trace that tells us
   exactly where they died and how they got there.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
