### ISSUE TITLE
set backupdir does not support double trailing slashes to include path info in filename

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#179]
```
What steps will reproduce the problem?
1. add to your vimrc:  set backupdir=~/tmp/vimbackupdir//
2. cd /some/dir
3. vim somefile
4. :w

What is the expected output?
~/tmp/vimbackupdir/ should have a filename with embedded path info so that you 
can edit the same filename in different directories without overwriting. The 
same way that "set directory" handles it for swap files.

What do you see instead?
Files in backupdir have only the filename.


What version of the product are you using? On what operating system?
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 12 2013 08:50:31)
Ubuntu 12.04.2 LTS

```

Original issue reported on code.google.com by `mattm@chromium.org` on 13 Nov 2013 at 11:44

**Comment by tforgione** [comment]
Any news on this ?

**Comment by chrisbra** [comment]
> Any news on this ?

It is still in the todo list.

Best,

## Christian

Eingebildete Leute haben mir Leid getan, denn sie tragen ja ihren
Trost mit sich.
        -- George Eliot (eigentlich Mary Ann Evans)

**Comment by vim-ml** [comment]
On 2015-11-18, Christian Brabandt wrote:
> > Any news on this ?
> 
> It is still in the todo list.

Do you have an updated patch for this?  I tried applying the one
I have from December, 2013, and unsurprisingly, it failed.

Regards,
Gary

**Comment by vim-ml** [comment]
On Do, 29 Jun 2017, Gary Johnson wrote:

> On 2015-11-18, Christian Brabandt wrote:
> > > Any news on this ?
> > 
> > It is still in the todo list.
> 
> Do you have an updated patch for this?  I tried applying the one
> I have from December, 2013, and unsurprisingly, it failed.

Oh thanks for noticing me. I'll look into it. 

Best,
Christian
-- 
Schließlich erreicht jeder Mensch jedes Ziel. Er muß es nur genügend
weit zurückstecken.
		-- Hans Söhnker

**Comment by chrisbra** [comment]
Updated patch, including a test can be found [here](https://github.com/chrisbra/vim-mq-patches/blob/master/backupdir)

**Comment by vim-ml** [comment]
> On Do, 29 Jun 2017, Gary Johnson wrote:
> 
> > On 2015-11-18, Christian Brabandt wrote:
> > > > Any news on this ?
> > > 
> > > It is still in the todo list.
> > 
> > Do you have an updated patch for this?  I tried applying the one
> > I have from December, 2013, and unsurprisingly, it failed.

I have updated the patch and included a test. It is available here:
https://github.com/chrisbra/vim-mq-patches/blob/master/backupdir
and I attach it for reference here as well.

Best,
Christian
-- 
Alles wahre Aperçu kommt aus einer Folge und bringt Folge. Es ist 
ein Mittelglied einer großen, produktiv aufsteigenden Kette.
		-- Goethe, Maximen und Reflektionen, Nr. 26

**Comment by vim-ml** [comment]
On 2017-06-30, Christian Brabandt wrote:
> 
> > On Do, 29 Jun 2017, Gary Johnson wrote:
> > 
> > > On 2015-11-18, Christian Brabandt wrote:
> > > > > Any news on this ?
> > > > 
> > > > It is still in the todo list.
> > > 
> > > Do you have an updated patch for this?  I tried applying the one
> > > I have from December, 2013, and unsurprisingly, it failed.
> 
> I have updated the patch and included a test. It is available here:
> https://github.com/chrisbra/vim-mq-patches/blob/master/backupdir
> and I attach it for reference here as well.

Thank you.  It doesn't seem to be working, though.  I updated to Vim
8.0.691, applied the patch, built and installed on a system running
Red Hat Enterprise Linux Server release 7.2.

    $ vim
    :set backup? backupdir?
      backup
      backupdir=~/tmp/vimbackup//

    :e ~/hello.txt
    " Make some changes.
    :wq
    $ ls ~/tmp/vimbackup
    hello.txt~

Regards,
Gary

**Comment by vim-ml** [comment]
On Fr, 30 Jun 2017, Gary Johnson wrote:

> Thank you.  It doesn't seem to be working, though.  I updated to Vim
> 8.0.691, applied the patch, built and installed on a system running
> Red Hat Enterprise Linux Server release 7.2.
> 
>     $ vim
>     :set backup? backupdir?
>       backup
>       backupdir=~/tmp/vimbackup//
> 
>     :e ~/hello.txt
>     " Make some changes.
>     :wq
>     $ ls ~/tmp/vimbackup
>     hello.txt~

Hm, I tested it and even included a test. Are you sure, you included the 
patch in the vim you have been running?

Best,
Christian
-- 
Wer sich zu groß fühlt, um kleine Aufgaben zu erfüllen, ist zu klein,
um mit großen Aufgaben betraut zu werden.
		-- Jacques Tati

**Comment by vim-ml** [comment]
On 2017-06-30, Christian Brabandt wrote:
> On Fr, 30 Jun 2017, Gary Johnson wrote:
> 
> > Thank you.  It doesn't seem to be working, though.  I updated to Vim
> > 8.0.691, applied the patch, built and installed on a system running
> > Red Hat Enterprise Linux Server release 7.2.
> > 
> >     $ vim
> >     :set backup? backupdir?
> >       backup
> >       backupdir=~/tmp/vimbackup//
> > 
> >     :e ~/hello.txt
> >     " Make some changes.
> >     :wq
> >     $ ls ~/tmp/vimbackup
> >     hello.txt~
> 
> Hm, I tested it and even included a test. Are you sure, you included the 
> patch in the vim you have been running?

As sure as I know how to be.  I applied the patch to a system at
home and to one at work.  Both fail the same way.  I ran "patch
--dry-run -p1 < ~/.vim/backupdir.patch" again on the second system
to check and it reported that the patches were already there.

Running the test gives me just this and an empty test_backup.res
file.

    $ make test_backup.res
    VIMRUNTIME=../../runtime; export VIMRUNTIME;  ../vim -f  -u unix.vim -U NONE --noplugin --not-a-term -S runtest.vim test_backup.vim

Regards,
Gary

**Comment by codenara** [comment]
This bug still exists.

I tested this using Vim 8.1.239 x64 on Windows 10 x64.

Vim 8.1.239 x64 for Windows was downloaded from
https://github.com/vim/vim-win32-installer/releases

Is there any plan to fix this bug?

Regards~

**Comment by vim-ml** [comment]
On 2018-08-07, Bram Moolenaar wrote:
> Closed #179 via b782ba4.

Thank you!

Regards,
Gary
