### ISSUE TITLE
IncSearch highlighting remains active after using `C-g` in an empty search command line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2267]
- `vim --version`: 8.0.1238
- Operating system/version: Linux/Ubuntu 16.04
- Terminal name/version: rxvt-unicode 9.22
- `$TERM`: xterm-256color

Start Vim like this to edit 2 files:

    vim --clean +'set incsearch hlsearch | colo desert' -O file1 file2

Search for a pattern in the 1st window. Then, press `/` to begin a new search, but don't write anything, just press `C-g` a few times to cycle between the matches of the last search (`:h c^g`). Validate the search or hit Escape to cancel. The highlighting due to the `'incsearch'` option stays active. And if you go to the next window, it follows a region of text surrounding the cursor.

Here's a [gif to illustrate](https://imgur.com/a/rui9i) (here the colorscheme is `desert`, in which the `IncSearch` highlight group seems to be green).

**Comment by osa1** [comment]
See also https://github.com/neovim/neovim/pull/7463#issuecomment-340686554

**Comment by haya14busa** [comment]
Hmm... Thank you for the report. It seems  patch 8.0.1238 https://github.com/vim/vim/commit/2e51d9a0972080b087d566608472928d5b7b35d7 introduced this bug.

(so, maybe reported vim version is wrong. I can tell 8.0.1238 is included from the posted GIF)

Can you try this patch? I didn't write tests yet, but I think it fixes the bugs.
 
```vim
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 717a01224..ac447b26e 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1945,6 +1945,7 @@ cmdline_changed:
 	    {
 		i = 0;
 		SET_NO_HLSEARCH(TRUE); /* turn off previous highlight */
+		redraw_all_later(SOME_VALID);
 	    }
 	    else
 	    {
@@ -2082,7 +2083,7 @@ returncmd:
 	curwin->w_botline = old_botline;
 	highlight_match = FALSE;
 	validate_cursor();	/* needed for TAB */
-	redraw_later(SOME_VALID);
+	redraw_all_later(SOME_VALID);
     }
 #endif
 ```

**Comment by lacygoill** [comment]
@haya14busa Ah yes you're right, the reported version was wrong, it's indeed `8.0.1238` and not `8.0.1236`. I've fixed the original post. Regarding the patch, I don't know how to apply/test it, but I'm going to try (after googling a little), and will report back if I get a result, unless someone else is able to test before.

**Comment by haya14busa** [comment]
Uploaded the patch to gist.  https://gist.github.com/haya14busa/853a42f8c9960e1419b457ac18c1c4c2

You can apply the patch by following command.
```
$ curl https://gist.githubusercontent.com/haya14busa/853a42f8c9960e1419b457ac18c1c4c2/raw/db0d016236349a3ed1cdb867050866d5180bdac6/incsearch-fix.patch | patch -p1
```

**Comment by lacygoill** [comment]
Maybe I made a mistake, but it doesn't seem to fix the issue. I tried to apply the patch by executing the command you gave, directly from the directory in which I've cloned Vim's repository, and received this output:

    curl https://gist.githubusercontent.com/haya14busa/853a42f8c9960e1419b457ac18c1c4c2/raw/db0d016236349a3ed1cdb867050866d5180bdac6/incsearch-fix.patch | patch -p1
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
    100   509  100   509    0     0    918      0 --:--:-- --:--:-- --:--:--   918
    patching file src/ex_getln.c
    patch unexpectedly ends in middle of line
    Hunk #2 succeeded at 2083 with fuzz 2.

I configured like I usually do:

    ./configure --enable-cscope                                                      \
              --enable-fail-if-missing                                             \
              --enable-gui=gtk2                                                    \
              --enable-luainterp=dynamic                                           \
              --enable-multibyte                                                   \
              --enable-perlinterp=yes                                              \
              --enable-python3interp=yes                                           \
              --enable-pythoninterp=yes                                            \
              --enable-rubyinterp=dynamic                                          \
              --enable-terminal                                                    \
              --prefix=/usr/local                                                  \
              --with-compiledby=user                                               \
              --with-features=huge                                                 \
              --with-luajit                                                        \
              --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ \
              --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/

I compiled:

    make

And tested with the command:

    ./src/vim --clean +'set incsearch hlsearch | colo desert' -O file1 file2

But the issue remains, `IncSearch` highlighting is still active after pressing `C-g` in an empty search command line.

I also tried to apply the patch manually (copy-paste the 2 new lines, deleted the old line inside `./src/ex_getln.c`), and the result was identical. But again, maybe I made a mistake when trying to apply the patch.

**Comment by haya14busa** [comment]
Thanks! Hmm... the patch fixed highlighting other windows when cancelling the search and when cmdline buffer become empty, but it doesn't fix IncSearch highlight issue.

**Comment by haya14busa** [comment]
Hmmm.... I don't know why but somehow I cannot reproduce IncSearch problem. 
Attached patch fixed the problem @osa1  reported.

**Comment by haya14busa** [comment]
> somehow I cannot reproduce IncSearch problem.

Sorry, I just overlooked the fact that I need to press  `<C-g>` while cmdline is empty (it's clearly stated in the title!). I could reproduce the problem too.

**Comment by chrisbra** [comment]
can confirm that the patch works.

**Comment by osa1** [comment]
I also confirm that this fixes the problem I reported (not sure about the current issue).

**Comment by haya14busa** [comment]
Oh, I found that original problem  @lacygoill reported is reproducible before  8.0.1238. 

My patch fixes the problem 8.0.1238 introduced.
- When cancelling the search while incremental searching with split window, other window remains to highlight the cmdline text. (It should highlight last searched pattern)
- When deleting cmdline text by `<c-h>`, `<C-w>`, `<C-u>`, etc... and the cmdline becomes empty, other windows still highlight previous cmdline text. (It should not highlight anything)

When writing patch 8.0.1238, I didn't notice the fact that now that incsearch & hlsearch highlight matches in other windows too,  we need to redraw other windows, not only the current window.

**Comment by lacygoill** [comment]
Yes, the patch may work to fix the issue mentioned by @osa1 but it doesn't fix the current issue. I can still reproduce it.

**Comment by lacygoill** [comment]
FWIW, this is how I fixed it:

    cno <expr>  <tab>    <sid>c_tab(1)
    cno <expr>  <s-tab>  <sid>c_tab(0)

    fu! s:c_tab(fwd) abort
        return getcmdtype() =~ '[?/]'
        \?     !empty(getcmdline())
        \?         a:fwd ? "\<c-g>" : "\<c-t>"
        \:         "\<up>"
        \:         feedkeys(a:fwd ? "\<tab>" : "\<s-tab>", 'int')[1]
    endfu

**Comment by haya14busa** [comment]
Can you re-open this issue? It's problem of Vim itself, so we need to fix it.

**Comment by haya14busa** [comment]
Hi, @chrisbra !

btw, are `ctrl-g/t`  commands expected to be used when search command-line text is empty?
I couldn't find the spec in help.

Also, I found another problem that when we move the cursor by `ctrl-g/t` while command-line text is empty, `<Esc>` (or `<C-c>`) won't move the cursor to the original position.

**Comment by h-east** [comment]
How about this patch?
```patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 717a012..5522c16 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1717,6 +1717,9 @@ getcmdline(
 		    pos_T  t;
 		    int    search_flags = SEARCH_NOOF;
 
+		    if (ccline.cmdlen == 0)
+			goto cmdline_not_changed;
+
 		    save_last_search_pattern();
 		    cursor_off();
 		    out_flush();
```

**Comment by chrisbra** [comment]
> btw, are ctrl-g/t commands expected to be used when search command-line text is empty?
I couldn't find the spec in help.

I certainly would not expect them to be used. Is that a problem currently? 

> Also, I found another problem that when we move the cursor by ctrl-g/t while command-line text is empty, <Esc> (or <C-c>) won't move the cursor to the original position.

that should then be fixed, I think @h-east patch fixes that, thanks for that.

**Comment by brammool** [comment]
> Hmm... Thank you for the report. It seems  patch 8.0.1238 https://github.com/vim/vim/commit/2e51d9a0972080b087d566608472928d5b7b35d7 introduce this bug.
> 
> (so, maybe reported vim version is wrong. I can tell 8.0.1238 is included from the posted GIF)
> 
> Can you try this patch? I didn't write tests yet, but I think it fixes the bugs.
>  
> ```vim
> diff --git a/src/ex_getln.c b/src/ex_getln.c
> index 717a01224..ac447b26e 100644
> --- a/src/ex_getln.c
> +++ b/src/ex_getln.c
> @@ -1945,6 +1945,7 @@ cmdline_changed:
>  	    {
>  		i = 0;
>  		SET_NO_HLSEARCH(TRUE); /* turn off previous highlight */
> +		redraw_all_later(SOME_VALID);
>  	    }
>  	    else
>  	    {
> @@ -2082,7 +2083,7 @@ returncmd:
>  	curwin->w_botline = old_botline;
>  	highlight_match = FALSE;
>  	validate_cursor();	/* needed for TAB */
> -	redraw_later(SOME_VALID);
> +	redraw_all_later(SOME_VALID);
>      }
>  #endif
>  ```

So we need this plus the other patch?  Can you make a pull request for
that (and bonus points if you can write a test :-).

-- 
VOICE OVER: As the horrendous Black Beast lunged forward, escape for Arthur
            and his knights seemed hopeless,  when, suddenly ... the animator
            suffered a fatal heart attack.
ANIMATOR:   Aaaaagh!
VOICE OVER: The cartoon peril was no more ... The Quest for Holy Grail could
            continue.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I'am going to submit a patch. I just noticed another bug, that needs to be fixed. So will send an patch containing those three fixes (and some tests).

**Comment by chrisbra** [comment]
patch sent to [vim-dev](https://groups.google.com/d/msg/vim_dev/fpNLqrMR5ZQ/g8SnNEPdBgAJ)

**Comment by haya14busa** [comment]
Thank you for your work!!!
