### ISSUE TITLE
":next" fails inside a try conditional when the next argument is not readable

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5451]
**Describe the bug**

I have a mapping to cycle through the entries in the arglist and wrap around the end.
It can be boiled down to:

    nno ]a :try \| next \| catch \| first \| endtry<cr>

The mapping fails to visit the next argument when it encounters a file which is not readable.
It's because of `:next` which behaves inconsistently depending on whether it's inside a `:try` conditional.

**To Reproduce**

Create 3 files:

    touch /tmp/file{1..3}

Change the owner of the third file to the root user and make it readable only by root:

    sudo chown root:root /tmp/file3 && sudo chmod 600 /tmp/file3

Start Vim like this:

    vim -Nu NONE /tmp/file{1..3}

Ask Vim to visit the next 2 arguments in the arglist by executing `:next` from a `:try` conditional twice:

    :try | next | endtry
    :try | next | endtry

`:echo expand('%:p')` reports that the current buffer is `/tmp/file3` (it's not read from the file though; hence the `[Permission Denied]` message, which is visible on the command-line if you don't have the `F` flag in `'shortmess'`).

    :echo expand('%:p')
    " /tmp/file3

`:args` reports that the current argument is still `/tmp/file2`.

    :args
    " /tmp/file1   [/tmp/file2] /tmp/file3
    "              ^^^^^^^^^^^^

**Expected behavior**

`:echo expand('%:p')` reports that the current buffer is `/tmp/file3`.
`:args` reports that the current argument is `/tmp/file3`, and not `/tmp/file2`.

**Environment**

 - Vim version: 8.2 Included patches: 1-96
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

If you repeat the same experiment without the `:try` conditional, `:next` correctly changes the current argument to `/tmp/file3`.

    vim -Nu NONE /tmp/file{1..3}
    :next
    :next
    :echo expand('%:p')
    " /tmp/file3
    :args
    " /tmp/file1   /tmp/file2   [/tmp/file3]
    "                           ^^^^^^^^^^^^

This behavior is inconsistent:

   - inside a `:try` conditional, `:next` fails to change the current argument if the next one is not readable
   - outside a `:try` conditional, `:next` succeeds in changing the current argument even if the next one is not readable

---

I've noticed something else. If the next argument is not readable and:

 - `'hidden'` is set, `:try | next | endtry` fails to change the current argument, but `:e foo | try | next | endtry` succeeds:

       vim -Nu NONE /tmp/file{1..3}
       :try | next | endtry
       :try | next | endtry
       :args
       " /tmp/file1   [/tmp/file2] /tmp/file3
       "              ^^^^^^^^^^^^
       :set hidden | e foo
       :try | next | endtry
       :args
       " /tmp/file1   /tmp/file2   [/tmp/file3]
       "                           ^^^^^^^^^^^^

 - `'hidden'` is not set, `:try | next | endtry` fails, and `:e foo | try | next | endtry` fails too:

       vim -Nu NONE /tmp/file{1..3}
       :try | next | endtry
       :try | next | endtry
       :args
       " /tmp/file1   [/tmp/file2] /tmp/file3
       "              ^^^^^^^^^^^^
       :set nohidden | e foo
       :try | next | endtry
       :args
       " /tmp/file1   [/tmp/file2] /tmp/file3
       "              ^^^^^^^^^^^^

**Comment by brammool** [comment]
This looks like it's working as intended.  Without try/catch an error is given and Vim continues with the command as well as it can.  With try/catch the first error causes the command to abort and get to the "catch" part.   The difference in behavior is intentional.

**Comment by lacygoill** [comment]
Thank you very much for the explanation.

However:

> With try/catch the first error causes the command to abort and get to the "catch" part.

Vim doesn't get to the catch part.

    touch /tmp/file{1..3}
    sudo chown root:root /tmp/file3 && sudo chmod 600 /tmp/file3
    vim -Nu NONE /tmp/file{1..3}
    :try | next | catch | unsilent echom 'Vim got to the catch part' | endtry
    :try | next | catch | unsilent echom 'Vim got to the catch part' | endtry

This is unexpected; if an error is raised, I would expect to be able to catch it to react appropriately.
But I can't. In the previous example, when Vim gets to the catch part, it should log the message "Vim got to the catch part"; it does not; `:messages` does not contain this message.

**Comment by lacygoill** [comment]
This is why my mapping was broken originally.

Since the catch clause is not processed, I thought that there was no "real" error, and that the behavior of `:next` was inconsistent inside/outside a `:try`. Now according to your explanation, it seems that the issue is a bit different; there is an error, but for some reason it can't be caught.

Anyway, I've fixed my mappings by refactoring the code so that it doesn't use a `:try` conditional at all:

    nno <silent> [a :<c-u>call <sid>move_in_arglist('[a')<cr>
    nno <silent> ]a :<c-u>call <sid>move_in_arglist(']a')<cr>
    fu s:move_in_arglist(lhs) abort
        if argc() < 2
            echohl ErrorMsg | echo 'E163: There is only one file to edit' | echohl NONE
            return
        endif
        if a:lhs is# ']a' && argidx() == argc() - 1
            first
        elseif a:lhs is# '[a' && argidx() == 0
            last
        elseif a:lhs is# ']a'
            next
        elseif a:lhs =~# '[a'
            prev
        endif
    endfu

**Comment by brammool** [comment]
> Thank you very much for the explanation.
> 
> However:
> 
> > With try/catch the first error causes the command to abort and get to the "catch" part.
> 
> Vim doesn't get to the catch part.
> 
>     touch /tmp/file{1..3}
>     sudo chown root:root /tmp/file3 && sudo chmod 600 /tmp/file3
>     vim -Nu NONE /tmp/file{1..3}
>     :try | next | catch | unsilent echom 'Vim got to the catch part' | endtry
> 
> This is unexpected; if an error is raised, I would expect to be able to catch it to react appropriately.
> But I can't. In the previous example, when Vim gets to the catch part,
> it should log the message "Vim got to the catch part"; it does not;
> `:messages` does not contain this message.

The "permission denied" message is not a real error message, therefore
there is nothing to catch.

When :next fails I still see ":args" show the failed file as the current
entry.  I'm not sure why you see something else.

-- 
A parent can be arrested if his child cannot hold back a burp during a church
service.
		[real standing law in Nebraska, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
