### ISSUE TITLE
Multiple line editing is slow/laggy

### ISSUE THREAD

**Issue by jclsn** [vim/vim#8082]
**Describe the bug**
When you edit multiple lines by entering visual mode and then entering insert mode with ``Shift + i``
the editing is rather slow. It takes like a second for the changes to occur. Can this be improved?
It was fixed in Neovim. Was hoping that it can be fixed here too.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Enter visual mode
2. Select multiple lines
3. Press ``Shift+i`` to enter insert mode
4. Edit the lines and press ``Esc``

**Expected behavior**
Editits should be applied in an instant

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: Manjaro
 - Terminal: Konsole

**Comment by chrisbra** [comment]
did you try using `vim --clean`?

**Comment by jclsn** [comment]
You mean start with empty vimrc? I don’t think that plugins are the problem, but will try later.

**Comment by lacygoill** [comment]
> I don’t think that plugins are the problem

We can't be sure of that until you provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  See [here](https://github.com/chrisbra/vim_faq/blob/7f9c65c91d01e289a92b9e43a70ee2becadd66ce/vim_faq.txt#L1153-L1228) for how to get one.  Note that what is written there is not limited to the vimrc; you can use the same kind of technique to third-party plugins.  But the bigger and more complex a plugin is, the more time-consuming the task is.

**Comment by jclsn** [comment]
Okay, yes it is gone when I use ``vim --clean``. But then I am wondering why the same problem doesn't happen in neovim. I think there is still room for improvement, but I guess as long as it doesn't happen in standard clean Vim, no one will bother improving it.

**Comment by lacygoill** [comment]
> I guess as long as it doesn't happen in standard clean Vim, no one will bother improving it.

About a year ago, I found [an issue](https://github.com/vim/vim/issues/5079) where Vim was lagging while cycling through the entries inside the pum.  Here's the minimal working example I posted:

    vim -Nu NONE +'setl cul' +'set ft=vim|syn enable|/readline#yank' +'setl noro|pu=\"th\"|startinsert!' <(curl -s https://raw.githubusercontent.com/lacygoill/vim-readline/master/autoload/readline.vim)

Notice the part after `vim -Nu NONE`:

    +'setl cul' +'set ft=vim|syn enable|/readline#yank' +'setl noro|pu=\"th\"|startinsert!' <(curl -s https://raw.githubusercontent.com/lacygoill/vim-readline/master/autoload/readline.vim)

All of that is not in "standard clean Vim".  The issue was fixed a week later.

**Comment by jclsn** [comment]
@lacygoill I'd rather live with the bug than prepare such an extensive example. There is also no need for an example. You just need to insert a few lines and try to edit them. It would probably be more important to find out what plugin is causing it.

**Comment by chrisbra** [comment]
well, try to reproduce to a minimal test case. This may be helpful: https://vimhelp.org/vim_faq.txt.html#faq-2.5

**Comment by jclsn** [comment]
The error still exists when I use ``vim -u NONE -U NONE -N -i NONE``, but not when I move/delete my .vimrc

@chrisbra I don't understand what you mean by minimal test case

**Comment by lacygoill** [comment]
> I'd rather live with the bug than prepare such an extensive example.

My point was that your guess:

> I guess as long as it doesn't happen in standard clean Vim, no one will bother improving it.

was wrong.  What you can live with is irrelevant.

**Comment by chrisbra** [comment]
`vim -u NONE -U NONE -N -i NONE` if that is true, then it should also occur with `vim --clean`. 

> I don't understand what you mean by minimal test case

Well, it may depend on settings, indent plugins, syntax plugins, global plugins, so it would be good to have a reproducible example with minimal options that matter and that can be run from the command line. BTW: You haven't yet specified what version you are running. Please output the complete `:version` output (and perhaps try with the latest master build in case you do not use it).

**Comment by jclsn** [comment]
@chrisbra No, the issue does occur with ``vim -u NONE -U NONE -N -i NONE``and does not with ``vim --clean``.
So you mean provide a vimrc that would be causing it? That would take me some time I guess.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 26 2021 00:21:09)
Included patches: 1-2653
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lelf -lacl -lattr -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm 

```

**Comment by jclsn** [comment]
Weirdly, I can put ``:finish``at the top of my vimrc and the bug persists. When I delete the vimrc though, it is gone...

**Comment by chrisbra** [comment]
>  No, the issue does occur with vim -u NONE -U NONE -N -i NONEand does not with vim --clean.

Hm, then it might be either defaults.vim or any of the ftplugin.vim filetype.vim or any of the default syntax plugins. Perhaps it's `ttimeout` or `ttimeoutlen` option?

**Comment by lacygoill** [comment]
> Hm, then it might be either defaults.vim or any of the ftplugin.vim filetype.vim or any of the default syntax plugins. Perhaps it's ttimeout or ttimeoutlen option?

If that's the case, then the OP should try this:

    :set timeout timeoutlen=3000 ttimeoutlen=100

Relevant help tag: [`:h 'ttimeoutlen'`](https://vimhelp.org/options.txt.html#'ttm').

**Comment by jclsn** [comment]
@chrisbra Nailed it! When I set ``ttimeoutlen=0``the issue is gone. Thank you :) I will see if this will cause problems with my key combinations but I don't think so.
