### ISSUE TITLE
Terminal rendering is slow after 7b5f45be2197403d631b5a3d633f6a20afdf806e

### ISSUE THREAD

**Issue by kg8m** [vim/vim#9058]
Hi. Vim's rendering of `:terminal` got slower after 7b5f45be2197403d631b5a3d633f6a20afdf806e. It is usually a little slow but sometimes critically slow.

### Steps to reproduce

1. [Shell] Clone a large repository
   ```sh
   $ git clone https://github.com/vim/vim /tmp/vim
   ```
1. [Shell] Change directory to the repository
   ```sh
   $ cd /tmp/vim
   ```
1. [Shell] Start Vim
   ```sh
   $ vim -u NONE
   ```
1. [Vim] Open `:terminal`
   ```
   :terminal ++rows=100
   ```
1. [Shell] List all files
   ```sh
   $ ls **/*
   ```

https://user-images.githubusercontent.com/694547/139068495-15c0b22e-c1f0-4748-9314-d1761428a07e.mp4

### Expected behaviour

Faster rendering is expected. The following video is the case of Vim built with [a patch which reverts 7b5f45be2197403d631b5a3d633f6a20afdf806e](https://github.com/vim/vim/files/7426195/vim_revert_7b5f45be2197403d631b5a3d633f6a20afdf806e.diff.txt).

https://user-images.githubusercontent.com/694547/139069087-fa8b7dd8-496a-4a7c-b0bf-92375e056128.mp4

### Operating system

macOS 10.15.7

### Version of Vim

iTerm2 (v8.2.3562)

**Comment by brammool** [comment]
Please check that the slowness is solved.

**Comment by kg8m** [comment]
Thank you for the patch. I checked it and confirmed the slowness was solved. I appreciate for your great work!!

But I have a new issue that `:terminal` has no colors, i.e., all characters are white, in some environments when `termguicolors` and `g:terminal_ansi_colors` are set. Steps to reproduce the issue are as shown below.

1. [Shell] Start vim as following:
   ```sh
   vim -u <(cat <<'EOF'
     set termguicolors
     let g:terminal_ansi_colors = ["#000000", "#F92672", "#BAED00", "#EBCE00", "#00BEF3", "#BAA0F0", "#71C0ED", "#EAEAEA", "#333333", "#FA397E", "#C1F600", "#FFE000", "#00C2F9", "#C6ABFF", "#79CEFF", "#FFFFFF"]
   EOF
   )
   ```
1. [Vim] Execute the command `:terminal`
1. [Shell in Vim] You will see a terminal window which has no colors

I checked 4 environments:

* Vim on macOS: OK (`:terminal` has colors)
* [MacVim](https://github.com/macvim-dev/macvim) on macOS: **NG (`:terminal` has no colors)**
  * I used [a patch of MacVim's head...Vim's head](https://github.com/vim/vim/files/7574800/macvim_fix_7b5f45be2197403d631b5a3d633f6a20afdf806e.diff.txt)
* Vim on CentOS 7: **NG (`:terminal` has no colors)**
* Vim on Amazon Linux: OK (`:terminal` has colors)

Could you point out what I should check on my environments for more information?

**Comment by lacygoill** [comment]
> I'm trying to investigate the cause of the issue.

Try to add this in your vimrc:

    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

See [`:help xterm-true-color`](https://vimhelp.org/term.txt.html#xterm-true-color).

If that doesn't work, and you think this is a bug, open a separate issue.
If you think this is config issue, ask for help on the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by kg8m** [comment]
@lacygoill Thank you for the feedback!! I tried to set `&t_8f` and `&t_8b` but the issue wasn't resolved (colon versions, e.g., `"\<Esc>[38:2:%lu:%lu:%lum"`, also didn't resolve it).

I think this is a bug because `:terminal` had colors in my all environments before 87fd0924e2d85213cc111ee7a5122f92216a37c7. So I'll create a separate issue. Your feedback helped me, thanks so much!!
